version: "3.7"

services:
  volleyball-fe:
    image: astnbnntt/volleyball:fe-latest
    ports:
      - "80:80"
    networks:
      - volleyball-network

  volleyball-api:
    image: astnbnntt/volleyball:api-latest
    ports:
      - "5001:5001"
    networks:
      - volleyball-network
    depends_on:
      - volleyball-db

  volleyball-db:
    image: astnbnntt/volleyball:db-latest
    ports:
      - "3306:3306"
    networks:
      - volleyball-network

networks:
  volleyball-network:
    driver: bridge
